environments:
  password: "xexzcbiusiffkddi"
twitter:
  apikey: "k9TA5ldaiGwiDN88oVYGefwLq"
  apisecret: "kCLqFTWVb71E9z9q5T7jF1nfFXQOU1lXVKnr9XpzdSfucinYs3"
sample:
  sample: "この文章はgem-Settingの開発テストです。"
